data = {
    Acre: {
        //Geral 
        Nome: "Acre",
        Capital: "Rio Branco",
        Data: "-",
        Area: "164.123,738 km²",
        Municipios: "22",
        Municipios_Importantes: "Rio Branco, Cruzeiro do Sul, Sena Madureira",
        Regiao: "Norte",
        Populacao: "906.876 hab.",
        Densidade: "5,53 hab./km²",
        Taxa_Urbana: "72.61%",
        Fuso: "UTC-5",
        //Economia
        Pib: "R$15,630 bilhões",
        Pib_Capita: "R$ 17.722,41",
        Arrecadacao: "R$ 140.022.841,56",
        Arrecadacao_Capita: "R$ 154,40",
        Produtos_agricolas: "Borracha, castanha-do-Brasil",
        Industrias: "Construção, Alimentos, Serviços industriais de utilidade pública",
        Exportacao: "-",
        //Politica
        Governador: "Gladson Cameli (PP)",
        Vice: "Major Rocha (PSL)",
        Presidente_Ass: "Nicolau Júnior (PP)",
        Qtd_Dep_Est: "24",
        Qtd_Dep_Fed: "8",
        Bancadas: "PP, MDB, PSB",
        Senador1: "Mailza Gomes (PP)",
        Senador2: "Márcio Bittar (PSL)",
        Senador3: "Sérgio Petecão (PSD)",
        //Social
        Expectativa_vida: "73,6 anos",
        Mortalidade_infantil: "17,6‰ nasc",
        Alfabetizacao: "84,8% ",
        IDH: "0,719",
        Renda: "R$ 917,00",
        Taxa_Ensino_Medio: "55,7%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "66,8%",
        //Racial
        Etnias: "Pardos (57,5%), Brancos (33%), Negros (7,8%), Indígenas e Asiáticos (2%)",
        Religioes: "Católicos (50,73%), Protestantes (32,7%), Espíritas (0,6%), Religiões Afro-brasileiras (0,0%), Outras (2,9%), Sem religião (11,8%), Religiões asiáticas (0,1%)",
        //Geografia
        Rios: "Rio Negro, Rio Moa, Breu, Tarauacá, Envira, Alto Purus, Purus, Iaco, Acre, Tejo, Rio Abunã e Rio Juruá",
        Climas: "Equatorial",
        Vegetacoes: "Floresta Equatorial",
        Relevos: "-",
        Divisoes: "-",
        //Imagens
        Imagem1: "img/imagens/ac/ac1.jpg",
        Imagem2: "img/imagens/ac/ac2.jpg",
        Imagem3: "img/imagens/ac/ac3.jpg", 
        Images: [
            "img/acre.png"
        ],
        Imagem_Estado: ["img/estados/acre.png"],
    },
    Alagoas: {
        Nome: "Alagoas",
        Capital: "Maceió",
        Data: "-",
        Area: "27.848,140 km²",
        Municipios: "102",
        Municipios_Importantes: "Maceió, Arapiraca, Rio Largo",
        Regiao: "Nordeste",
        Populacao: "3.365.351 hab",
        Densidade: "120,85 hab./km²",
        Taxa_Urbana: "73.64%",
        Fuso: "UTC-3",
        //Economia
        Pib: "R$52,843 bilhões",
        Pib_Capita: "R$15.653,51",
        Arrecadacao: "R$ 511.050.537,43",
        Arrecadacao_Capita: "R$ 151,86",
        Produtos_agricolas: "Abacaxi, coco, cana-de-açúcar, feijão, fumo, mandioca, algodão, arroz, milho",
        Industrias: "Construção, serviços Industriais de Utilidade Pública, Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "Renan Filho (MDB)",
        Vice: "Cargo Vazio",
        Presidente_Ass: "Marcelo Victor (SD)",
        Qtd_Dep_Est: "27",
        Qtd_Dep_Fed: "9",
        Bancadas: "MDB, PP, PRTB",
        Senador1: "Fernando Collor (PROS)",
        Senador2: "Renan Calheiros (MDB)",
        Senador3: "Rodrigo Cunha (PSDB)",
        //Social
        Expectativa_vida: "72,0 anos",
        Mortalidade_infantil: "14,45‰ nasc.",
        Alfabetizacao: "80,6%",
        IDH: "0,683",
        Renda: "R$796,00",
        Taxa_Ensino_Medio: "47,4%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "67,1%",
        //Racial
        Etnias: "Brancos (36%), Pardos (59%) e Negros (3%)",
        Religioes: "Católicos (72,3%), Protestantes (9,9%), Espíritas (0,5%), Religiões Afro-brasileiras (0,1%), Outras (6,5%), Sem religião (4,7%), Religiões Asiáticas (0,1%)",
        //Geografia
        Rios: "Camaragibe, o Mundaú, o Paraíba do Meio e o Coruripe",
        Climas: "Tropical e Semiárido",
        Vegetacoes: "Caatinga, Mata Atlântica e Vegetação Litorânea",
        Relevos: "-",
        Divisoes: "-",
        
        //Imaagens
        Imagem_Estado: ["img/estados/alagoas.png"],
        Imagem1: "img/imagens/al/al1.jpg",
        Imagem2: "img/imagens/al/al2.jpg",
        Imagem3: "img/imagens/al/al3.jpg",
        Images: [
            "img/alagoas.png"
        ]
    },
    Amapa: {
        Nome: "Amapá",
        Capital: "Macapá",
        Data: "13 de setembro de 1943",
        Area: "142.828,521 km²",
        Municipios: "16",
        Municipios_Importantes: "Macapá, Santana, Laranjal do Jari",
        Regiao: "Norte",
        Populacao: "877 613 hab.",
        Densidade: "6,14 hab./km²",
        Taxa_Urbana: "89.81",
        Fuso: "UTC−3, America/Belem",
        //Economia
        Pib: "R$15,480 bilhões",
        Pib_Capita: "R$19.405,00",
        Arrecadacao: " R$ 122.260.982,11",
        Arrecadacao_Capita: " R$ 139,31",
        Produtos_agricolas: "Castanha-do-Pará, Mandioca e Arroz",
        Industrias: "Serviços industriais de utilidade pública, Contrução, Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "Waldez Góes (PDT)",
        Vice: "Jaime Nunes (PROS)",
        Presidente_Ass: "Marcelo Victor (SD)",
        Qtd_Dep_Est: "24",
        Qtd_Dep_Fed: "8",
        Bancadas: "MDB, PP, PRTB",
        Senador1: "Randolfe Rodrigues (REDE)",
        Senador2: "Davi Alcolumbre (DEM)",
        Senador3: "Lucas Barreto (PSD)",
        //Social
        Expectativa_vida: "73,8 anos",
        Mortalidade_infantil: "23,5‰ nasc.",
        Alfabetizacao: "92,1%",
        IDH: "0,740",
        Renda: "R$893,00",
        Taxa_Ensino_Medio: "38,4%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "78,4%",
        //Racial
        Etnias: "Pardos (74,4%), Brancos (21,4%), Negros (4,5%), Amarelos ou Indígenas (0,8 %)",
        Religioes: "Católicos (70,89%%), Protestantes (28%), Espíritas (0,4%), Religiões Afro-brasileiras (0%), Outras (2,3%), Sem religião (5,5%), Religiões Asiáticas (0,3%)",
        //Geografia
        Rios: "Rio Amapá Grande; Rio Amapari; Rio Amazonas",
        Climas: "Equatorial",
        Vegetacoes: "Floresta de Várzea e Floresta de terra firme, Pântanos, Campos e Cerrados, Mangue",
        Relevos: "Planície Litorânea, baixo Planalto",
        Divisoes: "-",
        
        //Imaagens
        Imagem_Estado: ["img/estados/amapa.png"],
        Imagem1: "img/imagens/ap/ap1.jpg",
        Imagem2: "img/imagens/ap/ap2.jpg",
        Imagem3: "img/imagens/ap/ap3.jpg",
        Images: [
            "img/amapa.png"
        ]
    },
    Amazonas: {
        Nome: "Amazonas",
        Capital: "Manaus",
        Data: "-",
        Area: "1.559.167,878 km²",
        Municipios: "62",
        Municipios_Importantes: "Manaus, Parintins, Itacoatiara",
        Regiao: "Norte",
        Populacao: "4.269.995 hab.",
        Densidade: "2,74 hab./km²",
        Taxa_Urbana: "79.17%",
        Fuso: "UTC−04:00, UTC−5",
        //Economia
        Pib: "R$108,1 bilhões",
        Pib_Capita: "R$26.101,72",
        Arrecadacao: "R$ 1.672.789.793,51",
        Arrecadacao_Capita: "R$ 391,75",
        Produtos_agricolas: "Bovinos, suínos, galináceos, ovos de galinha, equinos, mandioca, leite, caprinos",
        Industrias: "Informática, eletrônicos e ópticos, Serviços industriais de utilidade pública, Bebidas",
        Exportacao: "-",
        //Politica
        Governador: "Wilson Lima (PSC)",
        Vice: "Carlos Almeida (PSDB)",
        Presidente_Ass: "Roberto Cidade (PV)",
        Qtd_Dep_Est: "24",
        Qtd_Dep_Fed: "8",
        Bancadas: "PP, PODE, PV",
        Senador1: "Eduardo Braga (MDB)",
        Senador2: "Omar Aziz (PSD)",
        Senador3: "Plínio Valério (PSDB)",
        //Social
        Expectativa_vida: "72,1 anos",
        Mortalidade_infantil: "18,8‰ nasc.",
        Alfabetizacao: "93,1%",
        IDH: "0,733",
        Renda: "R$852,00",
        Taxa_Ensino_Medio: "56,8%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "75,6%",
        //Racial
        Etnias: "Pardos(74,2%), Brancos(24,9%), Pretos(0,7%), Asiáticos ou Indígenas (0,2%)",
        Religioes: "Católicos (61,2%), protestantes (32,1%), pessoas sem religião (6,2%), espíritas (0,4%) e outras religiões (0,1%)",
        //Geografia
        Rios: "Rio Amazonas, Negro e Solimões, Madeira",
        Climas: "Equatorial",
        Vegetacoes: "Matas de terra firme, Várzea e Igapós",
        Relevos: "",
        Divisoes: "",
        
        //Imaagens
        Imagem_Estado: ["img/estados/amazonas.png"],
        Imagem1: "img/imagens/am/am1.jpg",
        Imagem2: "img/imagens/am/am2.jpg",
        Imagem3: "img/imagens/am/am3.jpg",
        Images: [
            "img/amazonas.png"
        ]
    },
    Bahia: {
        Nome: "Bahia",
        Capital: "Salvador",
        Data: "7 de setembro de 1822",
        Area: "564.733,177 Km²",
        Municipios: "417",
        Municipios_Importantes: "Salvador, Feira de Santana, Vitória da Conquista, Camaçari",
        Regiao: "Nordeste",
        Populacao: "14.985.284",
        Densidade: "26,54 hab./km²",
        Taxa_Urbana: "72.07%",
        Fuso: "UTC−3, América/Bahia",
        //Economia
        Pib: "R$ 286.239.541,12",
        Pib_Capita: "R$ 19.324,04",
        Arrecadacao: "R$ 3.281.551.913,92",
        Arrecadacao_Capita: " R$ 218,98",
        Produtos_agricolas: "algodão, cacau, soja e frutas tropicais como coco, mamão, manga, banana e guaraná, além de também produzir cana-de-açúcar, laranja, feijão e mandioca",
        Industrias: "Construção, Serviços industriais de utilidade pública, Derivados de petróleo e biocombustíveis",
        Exportacao: "-",
        //Politica
        Governador: "Rui Costa (PT)",
        Vice: "João Leão (PP)",
        Presidente_Ass: "Adolfo Menezes (PSD)",
        Qtd_Dep_Est: "63",
        Qtd_Dep_Fed: "39",
        Bancadas: "PP, PT, PSD",
        Senador1: "Angelo Coronel (PSD)",
        Senador2: "Jaques Wagner (PT)",
        Senador3: "Otto Alencar (PSD)",
        //Social
        Expectativa_vida: "73,7 anos",
        Mortalidade_infantil: "16,6‰ nasc.",
        Alfabetizacao: "87%",
        IDH: "0,714",
        Renda: "R$965,00",
        Taxa_Ensino_Medio: "49,9%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "70%",
        //Racial
        Etnias: "Pardos (59,8%), Brancos (23%), Negros (16,8%), Asiáticos ou Indígenas (0,3%)",
        Religioes: "Catolicismo (65,2%). Protestantismo (17,4%), Espiritismo (1,1%), Religiões afro-brasileiras (0,3%), Outras (4%), Sem Religião (12%)",
        //Geografia
        Rios: "Rio São Francisco, Rio Paraguaçu, Rio de Contas",
        Climas: "Equatorial, tropical com estação seca e semiárido",
        Vegetacoes: "Caatinga, floresta tropical úmida e cerrado",
        Relevos: "planícies, planaltos, e depressões e as formas tabulares e planas (chapadas, chapadões, tabuleiros)",
        Divisoes: "",
        
        //Imaagens
        Imagem1: "img/imagens/ba/ba1.jpg",
        Imagem2: "img/imagens/ba/ba2.jpg",
        Imagem3: "img/imagens/ba/ba3.jpg",
        
        Images: [
            "img/bahia.jpg",
            "img/bahia2.svg",
            "img/bahia3.jpg",
            "img/bahia4.jpg"
        ],
        Imagem_Estado: [
            "img/estados/bahia.png", 
            "img/estados/bahia/ba2.png"
        ]
    },
    Ceara: {
        Nome: "Ceará",
        Capital: "Fortaleza",
        Data: "28 de Fevereiro de 1821",
        Area: "148.894,442 km²",
        Municipios: "184",
        Municipios_Importantes: "Fortaleza, Caucaia, Juazeiro do Norte",
        Regiao: "Nordeste",
        Populacao: "9.240.580 hab",
        Densidade: "62,06 hab./km²",
        Taxa_Urbana: "77,4%",
        Fuso: "UTC−3, America/Fortaleza",
        //Economia
        Pib: "R$155.904 bilhões",
        Pib_Capita: "R$17.178",
        Arrecadacao: " R$ 2.466.797.843,72",
        Arrecadacao_Capita: " R$ 266,95",
        Produtos_agricolas: " feijão, milho, arroz, algodão herbáceo, algodão arbóreo, castanha de caju, cana-de-açúcar, mandioca, mamona, tomate, banana, laranja, coco e uva",
        Industrias: "Contrução, Serviços industriais de utilidade pública, Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "Camilo Santana (PT)",
        Vice: "Izolda Cela (PDT)",
        Presidente_Ass: "Evandro Leitão (PDT)",
        Qtd_Dep_Est: "46",
        Qtd_Dep_Fed: "22",
        Bancadas: "PDT, PP, PT",
        Senador1: "Cid Gomes (PDT)",
        Senador2: "Eduardo Girão (PODE)",
        Senador3: "Tasso Jereissati (PSDB)",
        //Social
        Expectativa_vida: "74,5 anos",
        Mortalidade_infantil: "12,8‰ nasc",
        Alfabetizacao: "86,4%",
        IDH: "0,735",
        Renda: "R$1.028,00",
        Taxa_Ensino_Medio: "74,0%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "68,9%",
        //Racial
        Etnias: "Brancos (33,05%), Negros (3,03%), Pardos (63,39%)",
        Religioes: "Católicos (81,08%), Protestantes (14,6%), Espíritas (0,6%), Religiões Afro-brasileitas (0%), Outras (1,8%), Sem religião (4%), Religiões asiáticas (0,2%)",
        //Geografia
        Rios: "Rio Acaraú, rio Banabuiú, rio Coreaú, rio Curu, rio Jaguaribe, rio Parnaíba, rio Salgado",
        Climas: "Semiárido e Tropical",
        Vegetacoes: "Caatinga" ,
        Relevos: "",
        //Imagens
        Imagem1: "img/imagens/ce/ce1.jpg",
        Imagem2: "img/imagens/ce/ce2.png",
        Imagem3: "img/imagens/ce/ce3.jpg",
        Images: [
            "img/Ceara.png"
        ],
        Imagem_Estado: ["img/estados/ceara.png"],
    },
    DistritoFederal: {
        Nome: "Distrito Federal",
        Capital: "Brasília",
        Data: "21 de abril de 1960",
        Area: "	5.760,784 km²",
        Municipios: "33",
        Municipios_Importantes: "Ceilândia, Samambaia, Plano Piloto",
        Regiao: "Centro-Oeste",
        Populacao: "3.094.325 hab",
        Densidade: "537,14 hab./km² ",
        Taxa_Urbana: "96.62%",
        Fuso: "UTC−3, America/Sao_Paulo",

        //Economia
        Pib: "R$244.683 bilhões",
        Pib_Capita: "R$80.502,47",
        Arrecadacao: "R$ 11.135.437.924,55",
        Arrecadacao_Capita: "R$ 3.598,66",
        Produtos_agricolas: "Feijão, Milho, Soja",
        Industrias: "Construção, Serviços industriais de utilidade pública, Alimentos",
        Exportacao: "-",

        //Politica
        Governador: "Ibaneis Rocha ",
        Vice: "Paco Britto",
        Presidente_Ass: "",
        Qtd_Dep_Est: "24",
        Qtd_Dep_Fed: "8",
        Bancadas: "Avante, Republicanos, PDT",
        Senador1: "Reguffe (PODE)",
        Senador2: "Leila Barros (Cidadania)",
        Senador3: "Izalci Lucas(PSDB)",

        //Social
        Expectativa_vida: "78,1 anos",
        Mortalidade_infantil: "10,5‰ nasc",
        Alfabetizacao: "97,4%",
        IDH: "0,850",
        Renda: "R$ 2.475",
        Taxa_Ensino_Medio: "74,4%",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "94,1%",

        //Racial
        Etnias: "Brancos (49,15%), pardos (44,77%), Negros (4,80%), Asiáticos ou Indígenas (0,74%)",
        Religioes: "Católicos (55,88%), Protestantes (25,8%), Espíritas (3,5%), Religiões Afro-brasileiras (0,2%), Outras (3,7%), Sem religião (9,2%), Religiões asiáticas (1,0%)", 

        //Geografia
        Rios: "Rio Paranoá",
        Climas: "Tropical com estação seca ",
        Vegetacoes: "Cerrado, Mata ciliar",
        Relevos: "planaltos, planícies e várzeas",
        Divisoes: "",

        //Imagens
        Imagem_Estado: ["img/estados/distrito.png"],
        Imagem1: "img/imagens/df/df1.jpg",
        Imagem2: "img/imagens/df/df2.jpg",
        Imagem3: "img/imagens/df/df3.jpg",
        Images: [
            "img/DF.png"
        ]
    },
    EspiritoSanto: {
        Nome: "Espírito Santo",
        Capital: "Vitória",
        Data: " 23 de maio de 1535",
        Area: "46 095,583 km²",
        Municipios: "78",
        Municipios_Importantes: "Serra, Vila Velha, Vitória ",
        Regiao: "Sudeste",
        Populacao: " 4 108 508 hab ",
        Densidade: "89,13 hab./km² ",
        Taxa_Urbana: "85.29%",
        Fuso: " UTC−3, America/Sao_Paulo ",
        //Economia
        Pib: " R$ 137.020 bilhões ",
        Pib_Capita: " R$ 34.493,12 ",
        Arrecadacao: " R$ 2.493.791.843,61",
        Arrecadacao_Capita: " R$ 606,98",
        Produtos_agricolas: "Cana-de-Açúcar, Laranja, Coco-da-Baía, Café",
        Industrias: "Contrução, Extração de Minerais Metálicos, Serviços industriais de utilidade pública",
        Exportacao: "-",
        //Politica
        Governador: "Renato Casagrande (PSB)",
        Vice: "Jacqueline Moraes (PSB)",
        Presidente_Ass: "",
        Qtd_Dep_Est: "30",
        Qtd_Dep_Fed: "10",
        Bancadas: "PSB, Republicanos, PSL",
        Senador1: "Fabiano Contarato (PT)",
        Senador2: "Marcos do Val (PODE)",
        Senador3: "Rose de Freitas (MDB)",
        //Social
        Expectativa_vida: " 77,9 anos",
        Mortalidade_infantil: "8,4‰ nasc ",
        Alfabetizacao: " 92,5% ",
        IDH: " 0,772 ",
        Renda: "R$ 1.347,00",
        Taxa_Ensino_Medio: "65,1",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "81,4%S",
        //Racial
        Etnias: "Brancos (48,6%), Pardos (42,2%), Negros (8,4%), Asiáticos ou Indígenas (0,8%)",
        Religioes: "Católicos (57,04%), Protestantes(33,1%), Espíritas (1%), Religiões Afro-brasileiras (0,2%), Outras (2%), Sem religião (10,4%), Religiões asiáticas (1,1%)",
        //Geografia
        Rios: " Doce, o São Mateus, o Itaúnas ",
        Climas: " tropical de altitude, Tropical ",
        Vegetacoes: " floresta pluvial atlântica, campo rupestre ",
        Relevos: " zona de tabuleiros, zona serrana e planície costeira ",
        Divisoes: " ",
        //imagens
        Imagem_Estado: ["img/estados/espirito.png"],
        Imagem1: "img/imagens/es/es1.jpg",
        Imagem2: "img/imagens/es/es2.jpg",
        Imagem3: "img/imagens/es/es3.jpg",
        Images: [
            "img/ES.png"
        ]
    },
    Goias: {
        Nome: "Goiás",
        Capital: "Goiânia",
        Data: " 14 de novembro de 1963",
        Area: "340 111,783 km²",
        Municipios: "246",
        Municipios_Importantes: "Goiânia, Aparecida de Goiânia, Anápolis",
        Regiao: "Centro-Oeste",
        Populacao: "7.206.589 hab.",
        Densidade: "21,19 hab./km² ",
        Taxa_Urbana: "90.29",
        Fuso: "UTC−3, America/Sao_Paulo",
        //Economia
        Pib: "R$ 208,672 bilhões",
        Pib_Capita: "R$ 29.732 ",
        Arrecadacao: "R$ 2.291.038.566,71",
        Arrecadacao_Capita: " R$ 317,91",
        Produtos_agricolas: "Cana-de-açúcar, milho, soja, tomate, sorgo, feijão, girassol, alho, algodão, arroz, café, trigo",
        Industrias: "Contrução, Alimentos, Serviços industriais de utilidade pública",
        Exportacao: "-",
        //Politica
        Governador: "Ronaldo Caiado (DEM)",
        Vice: "Lincoln Tejota (Cidadania)",
        Presidente_Ass: "Lissauer Vieira (PSB)",
        Qtd_Dep_Est: "41",
        Qtd_Dep_Fed: "17",
        Bancadas: "PSDB, DEM, MDB",
        Senador1: "Jorge Kajuru (PODE)",
        Senador2: "Luiz Carlos do Carmo (MDB)",
        Senador3: "Vanderlan Cardoso (PSD)",
        //Social
        Expectativa_vida: "71,0 anos",
        Mortalidade_infantil: "19,3‰ nasc.",
        Alfabetizacao: "93,5%",
        IDH: "0,769 ",
        Renda: "R$ 1.258,00",
        Taxa_Ensino_Medio: "75,8%",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "81,3%",
        //Racial
        Etnias: "Pardos (50,9%), Brancos (43,6%), Negros (5,3%), Indígenas (0,2%)",
        Religioes: "Católicos (65,42%), Protestantes (28,1%), Espíritas (2,5%),	Religiões Afro-brasileiras(0,0%), Outras (2,5%), Sem religião (8,1%), Religiões asiáticas (0,0%)",
        //Geografia
        Rios: "Paranaíba, Aporé, Araguaia",
        Climas: "Tropical monçônico, tropical savânico e subtropical de altitude",
        Vegetacoes: " Cerrado, floresta Atlântica",
        Relevos: " planaltos, chapadas",
        Divisoes: " ",
        //Imagens
        Imagem_Estado: ["img/estados/goias.png"],
        Imagem1: "img/imagens/go/go1.JPG",
        Imagem2: "img/imagens/go/go2.JPG",
        Imagem3: "img/imagens/go/go3.jpg",
        Images: [
            "img/Goias.png"
        ]
    },
    Maranhao: {
        Nome: "Maranhão",
        Capital: "São Luís",
        Data: "8 de setembro de 1612",
        Area: "331 937,450 km²",
        Municipios: "217",
        Municipios_Importantes: "São Luís, Imperatriz, São José de Ribamar",
        Regiao: "Nordeste",
        Populacao: "7.153.262 hab",
        Densidade: "21,55 hab./km²",
        Taxa_Urbana: "63.07%",
        Fuso: "	UTC−3, America/Fortaleza",
        //Economia
        Pib: "R$ 98,179 bilhões",
        Pib_Capita: "R$ 13.956",
        Arrecadacao: " R$ 956.373.321,46",
        Arrecadacao_Capita: " R$ 133,70",
        Produtos_agricolas: "Soja, mandioca, arroz, milho",
        Industrias: "Serviços industriais de utilidade pública, Contrução, Metalurgia",
        Exportacao: "-",
        //Politica
        Governador: "Flávio Dino (PSB)",
        Vice: "Carlos Brandão (PSDB)",
        Presidente_Ass: "Othelino Neto (PCdoB)",
        Qtd_Dep_Est: "42",
        Qtd_Dep_Fed: "18",
        Bancadas: "PMDB, PV, PRB",
        Senador1: "Eliziane Gama (Cidadania)",
        Senador2: "Roberto Rocha (PSDB)",
        Senador3: "Weverton (PDT)",
        //Social
        Expectativa_vida: "70,3 anos",
        Mortalidade_infantil: "22,4‰ nasc.",
        Alfabetizacao: "80,7%",
        IDH: "0,687 ",
        Renda: "R$ 676,00",
        Taxa_Ensino_Medio: "66,1%",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "61,4%",
        //Racial
        Etnias: "Pardos (68,8%), Brancos (24,9%), Negros (5,5%), Asiáticos e Indígenas (0,7%)",
        Religioes: "Católicos (78,04%), Evangélicos (17,25%), Espíritas (0,2%), Religiões Afro Brasileiras (0,0%), Outras (1,5%), Sem Religião (6,3%), Religiões Asiáticas (0,3%)",
        //Geografia
        Rios: "Gurupi, Turiaçu, Maracaçumé, Pindaré, Grajaú, Mearim, Itapecuru, Parnaíba",
        Climas: "Tropical ",
        Vegetacoes: "campos de inundação (Baixada Maranhense), mangues e arbustos",
        Relevos: "baixada litorânea e o planalto",
        Divisoes: " ",
        //Imagens
        Imagem_Estado: ["img/estados/maranhao.png"],
        Imagem1: "img/imagens/ma/ma1.jpg",
        Imagem2: "img/imagens/ma/ma2.jpg",
        Imagem3: "img/imagens/ma/ma3.jpg",
        Images: [
            "img/Maranhao.png"
        ]
    },
    MatoGrosso: {
        Nome: "Mato Grosso",
        Capital: "Cuiabá",
        Data: "-",
        Area: "903 207,050 km²",
        Municipios: "141",
        Municipios_Importantes: "Cuiabá, Várzea Grande, Rondonópolis",
        Regiao: "Centro-Oeste",
        Populacao: "3.567.234 hab.",
        Densidade: "3,95 hab./km²",
        Taxa_Urbana: "81.90%", 
        Fuso: "UTC−04:00",
        //Economia
        Pib: "R$ 142,122 bilhões",
        Pib_Capita: "R$ 40.787,32",
        Arrecadacao: " R$ 1.546.313.142,13",
        Arrecadacao_Capita: " R$ 433,48",
        Produtos_agricolas: "Soja, feijão, Cana-de-açúcar",
        Industrias: "Alimentos, Construção, Serviços Industriais de Utilidade Pública",
        Exportacao: "-",
        //Politica
        Governador: "Mauro Mendes (DEM)",
        Vice: "Otaviano Pivetta (PDT)",
        Presidente_Ass: "Eduardo Botelho (DEM)",
        Qtd_Dep_Est: "24",
        Qtd_Dep_Fed: "8",
        Bancadas: "MDB, PSL, PSB",
        Senador1: "Jayme Campos (DEM)",
        Senador2: "Carlos Fávaro (PSD)",
        Senador3: "Wellington Fagundes (PL)",
        //Social
        Expectativa_vida: "74,0 anos",
        Mortalidade_infantil: "17,3% nasc.",
        Alfabetizacao: "92,2%",
        IDH: "0,774",
        Renda: "R$ 1.401,00",
        Taxa_Ensino_Medio: "77,2%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "78,5%",
        //Racial
        Etnias: "Pardos (52,7%), Brancos (27,1%), Negros (7,4%), Indígenas e Asiáticos (1,1%)",
        Religioes: "Católicos (79,63%), Protestantes (24,5%), Espíritas (1,3%), Religiões Afro-brasileiras (0,1%), Outras (3%), sem religião (6,6%) Religiões Asiáticas (1,1%)",
        //Geografia
        Rios: "Rio Araguaia, Rio Arinos, Rio Cuiabá",
        Climas: "Tropical Super-úmido de monção, tropical",
        Vegetacoes: "Cerrado, Pantanal, Floresta Amazônica" ,
        Relevos: " ",
        Divisoes: " ",
        //Imagens
        Imagem_Estado: ["img/estados/matogrosso.png"],
        Imagem1: "img/imagens/mt/mt1.jpg",
        Imagem2: "img/imagens/mt/mt2.jpg",
        Imagem3: "img/imagens/mt/mt3.jpg",
        Images: [
            "img/MT.png"
        ]
    },
    MatoGrossodoSul: {
        Nome: "Mato Grosso do Sul",
        Capital: "Campo Grande",
        Data: "Não sei",
        Area: "	357 145,532 km²",
        Municipios: "79",
        Municipios_Importantes: "Dourados, Três Lagoas, Corumbá",
        Regiao: "Centro Oeste",
        Populacao: "2.839.188 hab.",
        Densidade: "7,95 hab./km²",
        Taxa_Urbana: "85.64%",
        Fuso: "	UTC−04:00",
        //Economia
        Pib: "R$ 96.372.000",
        Pib_Capita: "R$ 35.520,45",
        Arrecadacao: " R$ 1.039.848.725,70",
        Arrecadacao_Capita: " R$ 366,25",
        Produtos_agricolas: "Açúcar, Soja, Carne Bovina",
        Industrias: "Serviços industriais de utilidade pública, Construção, Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "Reinaldo Azambuja (PSDB)",
        Vice: "Murilo Zauith (DEM)",
        Presidente_Ass: "Paulo Corrêa (PSDB)",
        Qtd_Dep_Est: "24",
        Qtd_Dep_Fed: "8",
        Bancadas: "PSDB, MDB, PT",
        Senador1: "Nelsinho Trad (PSD)",
        Senador2: "Simone Tebet (MDB)",
        Senador3: "Soraya Thronicke (PSL)",
        //Social
        Expectativa_vida: "75,3 anos",
        Mortalidade_infantil: "14,5‰ nasc.",
        Alfabetizacao: "93,0%",
        IDH: "0,766",
        Renda: "R$ 1.488,00",
        Taxa_Ensino_Medio: "67,4%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "83,8%",
        //Racial
        Etnias: "-",
        Religioes: "Católicos (63,70%),	Protestantes (26,5%), Espíritas (1,9%),	Religiões Afro-brasileiras (0,0%), Outras (3%), Sem religião (9,2%), Religiões asiáticas (2,0%)",
        //Geografia
        Rios: "Rio Paraná, rio Sucuriú, rio Verde, rio Pardo, rio Ivinhema",
        Climas: "Tropical",
        Vegetacoes: "Cerrado, Pampas, Mata Atlântica" ,
        Relevos: "Planaltos, patamares e chapadões",
        Divisoes: "",
        //Imagens
        Imagem_Estado: ["img/estados/matogrossodosul.png"],
        Imagem1: "img/imagens/ms/ms1.jpg",
        Imagem2: "img/imagens/ms/ms2.JPG",
        Imagem3: "img/imagens/ms/ms3.jpg",
        Images: [
            "img/MTS.png"
        ]
    },
    MinasGerais: {
        Nome: "Minas Gerais",
        Capital: "Belo Horizonte",
        Data: "2 de dezembro de 1720",
        Area: "586 522,122 km²",
        Municipios: "853",
        Municipios_Importantes: "Belo Horizonte, Uberlândia, Contagem",
        Regiao: "Sudeste",
        Populacao: "21.411.923 hab.",
        Densidade: "36,51 hab./km²",
        Fuso: "UTC−3, America/São Paulo",
        //Economia
        Pib: "R$ 576,199 bilhões",
        Pib_Capita: "R$ 27.282,00",
        Arrecadacao: " R$ 10.331.271.018,41",
        Arrecadacao_Capita: " R$ 482,50",
        Produtos_agricolas: "Café, cana-de-açúcar, milho, soja e feitão",
        Industrias: "17,8% Construção, 16,0% Extração de minerais metálicos, 12,2% Serviços industriais de utilidade pública, 11,5% Metalurgia, 11,4% Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "Romeu Zema (NOVO)",
        Vice: "Paulo Brant (PSDB)",
        Presidente_Ass: "Agostinho Patrus (PV)",
        Qtd_Dep_Est: "77",
        Qtd_Dep_Fed: "53",
        Bancadas: "PSL, PT, PL",
        Senador1: "Antonio Anastasia (PSD)",
        Senador2: "Carlos Viana (PSD)",
        Senador3: "Rodrigo Pacheco (PSD)",
        //Social
        Expectativa_vida: "77,0 anos",
        Mortalidade_infantil: "11,4‰ nasc.",
        Alfabetizacao: "92,3%",
        IDH: "0,787",
        Renda: "R$ 1.314,00",
        Taxa_Ensino_Medio: "78,2",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "79,3%",
        //Racial
        Etnias: "Brancos 45,4%, Pardos 44,3%, Negros 9,2%, amarelos ou indígenas 1,1%",
        Religioes: "Católicos (73,32%), Protestantes (20,2%), Espíritas (2,1%), Religiões Afro-brasileiras (0%), Outras (2,3%), Sem religião (39%), Religiões asiáticas (1,1%)",
        //Geografia
        Rios: "Rio das Velhas, rio Doce, rio Grande, São Francisco",
        Climas: "Tropical de monção, tropical de savana, subtropical úmido, subtropical oceânico, subtropical úmido de inverno seco, subtropical de altitude",
        Vegetacoes: "Cerrado, Mata Atlântica, Campos Rupestres e a mata seca" ,
        Relevos: "planaltos com escarpas e depressões",
        Divisoes: " ",
        //Imagens
        Imagem_Estado: ["img/estados/minas.png"],
        Imagem1: "img/imagens/mg/mg1.jpg",
        Imagem2: "img/imagens/mg/mg2.jpg",
        Imagem3: "img/imagens/mg/mg3.jpg",
        Images: [
            "img/MG.png"
        ]
    },
    Para: {
        Nome: "Pará",
        Capital: "Belém",
        Data: "",
        Area: "1 245 870,798 km²",
        Municipios: "144",
        Municipios_Importantes: "Ananindeua, Santarém, Marabá",
        Regiao: "Norte",
        Populacao: "8.777.124 hab.",
        Densidade: "7,04 hab./km²",
        Taxa_Urbana: "68.49%",
        Fuso: "UTC−3",
        //Economia
        Pib: "R$ 178,377 bilhões",
        Pib_Capita: "	R$ 20.734,60",
        Arrecadacao: " R$ 1.450.016.905,60",
        Arrecadacao_Capita: " R$ 165,20",
        Produtos_agricolas: "Mandioca, açaí, abacaxi, cacau, pimenta-do-reino, limão, coco, banana",
        Industrias: "Extração de minerais metálicos, Serviços industriais de utilidade pública, Construção",
        Exportacao: "-",
        //Politica
        Governador: "Helder Barbalho (MDB)",
        Vice: "Lúcio Vale (PL)",
        Presidente_Ass: "Francisco Melo (MDB)",
        Qtd_Dep_Est: "41",
        Qtd_Dep_Fed: "17",
        Bancadas: "MDB, PSDB, PL",
        Senador1: "Jader Barbalho (MDB)",
        Senador2: "Paulo Rocha (PT)",
        Senador3: "Zequinha Marinho (PSC)",
        //Social
        Expectativa_vida: "71,9 anos",
        Mortalidade_infantil: "17,1‰ nasc.",
        Alfabetizacao: "88,8%",
        IDH: "0,698",
        Renda: "R$ 883,00",
        Taxa_Ensino_Medio: "57,6%",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "69,4%",
        //Racial
        Etnias: "Pardos (73,0%), Brancos (23%), Pretos (3,5%), Indígenas ou Asiáticos (0,6%)",
        Religioes: "Católicos (66,55%),	Protestantes (25,8%), Espíritas (0,4%), Religiões Afro-brasileiras (0,1%), Outras (2,1%), Sem religião (7%), Religiões asiáticas (0,9%)",
        //Geografia
        Rios: "Rio Amazonas, rio Tapajós, rio Tocantins, rio Xingu, rio Jari, rio Pará",
        Climas: "Equatorial",
        Vegetacoes: "Mangues, campos, cerrados e floresta Amazônica",
        Relevos: "Baixo e plano",
        Divisoes: " ",

        //Imagens
        Imagem_Estado: ["img/estados/para.png"],
        Imagem1: "img/imagens/pa/pa1.jpg",
        Imagem2: "img/imagens/pa/pa2.jpg",
        Imagem3: "img/imagens/pa/pa3.jpg",
        Images: [
            "img/Para.png"
        ]
    },
    Paraiba: {
        Nome: "Paraíba",
        Capital: "João Pessoa",
        Data: " 15 de novembro de 1889.",
        Area: "	56 467,242 km²",
        Municipios: "223",
        Municipios_Importantes: "João Pessoa, Campina Grande, Santa Rita",
        Regiao: "Nordeste",
        Populacao: "4.059.905 hab",
        Densidade: "71,9 hab./km²",
        Taxa_Urbana: "75.37%",
        Fuso: "UTC−3",
        //Economia
        Pib: "64.374.000.000 ",
        Pib_Capita: "R$ 16.107,51",
        Arrecadacao: " R$ 736.152.961,99",
        Arrecadacao_Capita: " R$ 181,32",
        Produtos_agricolas: "arroz, feijão, café, mandioca, milho, castanha de caju, pimenta do reino, sisal, abacaxi e, principalmente, cana-de-açúcar",
        Industrias: "Contrução, Serviços industriais de utilidade pública, Couros e calçados",
        Exportacao: "-",
        //Politica
        Governador: "João Azevêdo (Cidadania)",
        Vice: "Lígia Feliciano (PDT)",
        Presidente_Ass: "",
        Qtd_Dep_Est: "36",
        Qtd_Dep_Fed: "12",
        Bancadas: "PSB, AVANTE, PODE",
        Senador1: "Daniella Ribeiro (PP)",
        Senador2: "Nilda Gondim (MDB)",
        Senador3: "Veneziano Vital do Rêgo (MDB)",
        //Social
        Expectativa_vida: "74,62 anos ",
        Mortalidade_infantil: "12,96‰ nasc",
        Alfabetizacao: "79,8%",
        IDH: "0,722",
        Renda: "R$ 892,00",
        Taxa_Ensino_Medio: "55,5%",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "72,2%",
        //Racial
        Etnias: "Pardos (52,948%), brancos (39,672%), pretos (5,611%), asiáticos e indígenas (1,238%)",
        Religioes: "Católicos (80,25%), Evangélicos (15,1%), Espíritas (0,6%), Religiões Afro-brasileiras (0,1%), Outras (1,4%), Sem religião (5,7%), Religiões asiáticas (0,1%)",
        //Geografia
        Rios: "Rio Piranhas, rio Piancó, rio Seridó",
        Climas: "Semiárido",
        Vegetacoes: "Caatinga",
        Relevos: " planície litorânea, Depressão Sertaneja, ",
        Divisoes: " ",
        //Imagens
        Imagem_Estado: ["img/estados/paraiba.png"],
        Imagem1: "img/imagens/pb/pb1.jpg",
        Imagem2: "img/imagens/pb/pb2.jpg",
        Imagem3: "img/imagens/pb/pb3.jpg",
        Images: [
            "img/Paraiba.png"
        ]
    },
    Parana: {
        Nome: "Paraná",
        Capital: "Curitiba",
        Data: "15 de novembro de 1889",
        Area: "199 307,922 km²",
        Municipios: "399",
        Municipios_Importantes: "Curitiba, Londrina, Maringá",
        Regiao: "Sul",
        Populacao: "11.597.484 hab",
        Densidade: "58,19 hab./km² ",
        Taxa_Urbana: "85.31",
        Fuso: "UTC−3, America/Sao_Paulo",
        //Economia
        Pib: "R$ 440.029 bilhões",
        Pib_Capita: "R$ 38.772,74",
        Arrecadacao: " R$ 7.516.507.204,80",
        Arrecadacao_Capita: " R$ 648,12",
        Produtos_agricolas: "Trigo, milho, soja",
        Industrias: "Serviços industriais de utilidade pública, Alimentos, Contrução",
        Exportacao: "-",
        //Politica
        Governador: "Ratinho Júnior (PSD)",
        Vice: "Darci Piana (PSD)",
        Presidente_Ass: "Ademar Traiano (PSDB)",
        Qtd_Dep_Est: "54",
        Qtd_Dep_Fed: "30",
        Bancadas: "PSD, PSB, PSL",
        Senador1: "Alvaro Dias (PODE)",
        Senador2: "Flávio Arns (PODE)",
        Senador3: "Oriovisto Guimarães (PODE)",
        //Social
        Expectativa_vida: "76,8 anos",
        Mortalidade_infantil: "8,9‰ nasc",
        Alfabetizacao: "95,4%",
        IDH: "0,792 ",
        Renda: "R$ 1.508",
        Taxa_Ensino_Medio: "75,7%",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "80,5%",
        //Racial
        Etnias: "Brancos (70,06%), pardos (25,35%), pretos (3,15%), amarelos (1,19%), indígenas (0,25%)",
        Religioes: "Católicos (69,82%), Protestantes (22,2%), Espíritas (1%), Religiões Afro-brasileiras (0%), Outras (2,6%), Sem religião (4,6%), Religiões asiáticas (2,9%)",
        //Geografia
        Rios: "Rio Paraná, rio Iguaçu, rio Ivaí",
        Climas: "Subtropical",
        Vegetacoes: "",
        Relevos: "planaltos montanhosos, planícies de aluvião",
        Divisoes: " ",
        //Imagens
        Imagem_Estado: ["img/estados/parana.png"],
        Imagem1: "img/imagens/pr/pr1.jpg",
        Imagem2: "img/imagens/pr/pr2.jpg",
        Imagem3: "img/imagens/pr/pr3.jpg",
        Images: [
            "img/Parana.png"
        ]
    },
    Pernambuco: {
        Nome: "Pernambuco",
        Capital: "Recife",
        Data: "Não sei",
        Area: "98 149,119 km²",
        Municipios: "185",
        Municipios_Importantes: "Recife, Jaboatão dos Guararapes, Olinda, Caruaru",
        Regiao: "Nordeste",
        Populacao: "9.674.793 hab.",
        Densidade: "98,57 hab./km²",
        Taxa_Urbana: "80.15%",
        Fuso: "UTC−3 e UTC−2",
        //Economia
        Pib: "R$ 197.853 bilhões",
        Pib_Capita: "R$ 20.702,30",
        Arrecadacao: " R$ 2.625.386.934,93",
        Arrecadacao_Capita: " R$ 271,36",
        Produtos_agricolas: "Açúcar, acerola, goiaba, uva, manga e coco",
        Industrias: "Construção, Serviços industriais de utilidade pública, Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "Paulo Câmara (PSB)",
        Vice: "Luciana Santos (PCdoB)",
        Presidente_Ass: "Eriberto Medeiros (PP)",
        Qtd_Dep_Est: "49",
        Qtd_Dep_Fed: "25",
        Bancadas: "PSB, PP, PSC",
        Senador1: "Humberto Costa (PT)",
        Senador2: "Jarbas Vasconselos (MDB)",
        Senador3: "Fernando Bezerra Coelho (MDB)",
        //Social
        Expectativa_vida: "74,3 anos",
        Mortalidade_infantil: "12,1‰ nasc.",
        Alfabetizacao: "88,1%;",
        IDH: "0,727",
        Renda: "R$ 897,00",
        Taxa_Ensino_Medio: "68,2%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "71,4%",
        //Racial
        Etnias: "brancos (36,6%), pretos (5,4%), pardos (57,6%), Amarelos e Indígenas (0,3%)",
        Religioes: "Católicos (63,84%), Protestantes (32,3%), Espíritas (0,4%), Religiões Afro-brasileiras (0,1%), Outras (1,8%), Sem religião (5,4%), Religiões asiáticas (1,7%)",
        //Geografia
        Rios: "Rio São Francisco, rio Capibaribe, rio Ipojuca, rio Una, rio Pajeú, rio Jaboatão",
        Climas: "tropical úmido, tropical de altitude, semiárido e semiárido muito quente",
        Vegetacoes: "Floresta tropical perene, floresta tropical semidecídua e caatinga" ,
        Relevos: "",
        //Imagens
        Imagem_Estado: ["img/estados/pernambuco.png"],
        Imagem1: "img/imagens/pe/pe1.png",
        Imagem2: "img/imagens/pe/pe2.jpg",
        Imagem3: "img/imagens/pe/pe3.jpg",
        Images: [
            "img/Pernambuco.png"
        ]
    },
    Piaui: {
        Nome: "Piauí",
        Capital: "Teresina",
        Data: "",
        Area: "251 755,485 km²",
        Municipios: "224",
        Municipios_Importantes: "Parnaíba, Picos, Piripiri",
        Regiao: "Nordeste",
        Populacao: "3.289.290 hab.",
        Densidade: "13,07 hab./km²",
        Taxa_Urbana: "65.77%",
        Fuso: "	UTC−3, America/Fortaleza",
        //Economia
        Pib: "R$ 45,359 bilhões",
        Pib_Capita: "R$ 14.089",
        Arrecadacao: " R$ 482.008.518,93",
        Arrecadacao_Capita: " R$ 146,54",
        Produtos_agricolas: "soja, algodão, arroz, cana-de-açúcar, mandioca",
        Industrias: "Construção, Serviços industriais de utilidade pública, Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "Wellington Dias (PT)",
        Vice: "Regina Sousa (PT)",
        Presidente_Ass: "Themístocles Filho (MDB)",
        Qtd_Dep_Est: "30",
        Qtd_Dep_Fed: "10",
        Bancadas: "MDB, PT, PP",
        Senador1: "Ciro Nogueira (PP)",
        Senador2: "Elmano Férrer (PP)",
        Senador3: "Marcelo Castro (MDB)",
        //Social
        Expectativa_vida: "70,9 anos",
        Mortalidade_infantil: "19,7‰ nasc.",
        Alfabetizacao: "82,8%",
        IDH: "0,646",
        Renda: "R$ 859",
        Taxa_Ensino_Medio: "64,2%",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "61,4%",
        //Racial
        Etnias: "Pardos	(69%), Brancos (24%), Pretos (7%), Amarelos (2,3%)",
        Religioes: "Católicos (87,93%), Protestantes (9,7%), Espíritas (0,3%), Religiões Afro-brasileiras (0,1%), Outras (1,4%), Sem religião (3,4%), Religiões asiáticas (0,0%)",
        //Geografia
        Rios: "Rio São Francisco, rio Parnaíba, Uruçui Preto",
        Climas: "Tropical de Savana, Semiárido",
        Vegetacoes: "Caatinga, Cerrado, Mata de Cocais",
        Relevos: "",
        Divisoes: " ",
        //Imagens
        Imagem_Estado: ["img/estados/piaui.png"],
        Imagem1: "img/imagens/pi/pi1.JPG",
        Imagem2: "img/imagens/pi/pi2.jfif",
        Imagem3: "img/imagens/pi/pi3.jpg",
        Images: [
            "img/Piaui.png"
        ]
    },
    RiodeJaneiro: {
        Nome: "Rio de Janeiro",
        Capital: "Rio de Janeiro",
        Data: "1 Março de 1595",
        Area: "43 750,426 km²",
        Municipios: "92",
        Municipios_Importantes: "Rio de Janeiro, São Gonçalo, Duque de Caxias",
        Regiao: "Sudeste",
        Populacao: "17.463.349 hab.",
        Densidade: "399,16 hab./km²",
        Taxa_Urbana: "96,7%",
        Fuso: "UTC−3, América/São Paulo",
        //Economia
        Pib: "R$ 758.859 bilhões",
        Pib_Capita: "R$ 44.222,00",
        Arrecadacao: " R$ 26.997.729.087,35",
        Arrecadacao_Capita: " R$ 1.545,97",
        Produtos_agricolas: "cana-de-açúcar, além de mandioca, tomate, arroz, feijão, milho, batata, laranja e banana",
        Industrias: "Extração de petróleo e gás natural, Construção, Serviços industriais de utilidade pública",
        Exportacao: "-",
        //Politica
        Governador: "Cláudio Castro (PL)",
        Vice: "Cargo Vazio",
        Presidente_Ass: "André Ceciliano (PT)",
        Qtd_Dep_Est: "70",
        Qtd_Dep_Fed: "46",
        Bancadas: "PSOL, DEM, Republicanos",
        Senador1: "Carlos Portinho (PL)",
        Senador2: "Flávio Bolsonaro (PL)",
        Senador3: "Romário (PL)",
        //Social
        Expectativa_vida: "76,5 anos ",
        Mortalidade_infantil: "11,1‰ nasc.",
        Alfabetizacao: "97,3%",
        IDH: "0,796",
        Renda: "R$ 1.723,00",
        Taxa_Ensino_Medio: "72,7",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "86%",
        //Racial
        Etnias: "Brancos (47,4%), Pardos (39,6%), Pretos (12,1%), Amarelos, Indígenas e não declarados (0,9%)",
        Religioes: "Católicos (49,83%), Protestantes (29,4%), Espíritas (4%), Religiões Afro-brasileiras (0,9%), Outras (4,3%), Sem religião (14,6%), Religiões asiáticas (1%);",
        //Geografia
        Rios: "Paraíba do Sul, Itabapoana, Macabu, Macaé",
        Climas: "Tropical",
        Vegetacoes: "Mata Atlântica, restingas, manguezais e campos de altitude" ,
        Relevos: "",
        Divisoes: "",
        //Imagens
        Imagem_Estado: ["img/estados/rio.png"],
        Imagem1: "img/imagens/rj/rj1.jpg",
        Imagem2: "img/imagens/rj/rj2.jpg",
        Imagem3: "img/imagens/rj/rj3.jpg",
        Images: [
            "img/RJ.png"
        ]
    },
    RioGrandedoNorte: {
        Nome: "Rio Grande do Norte",
        Capital: "Natal",
        Data: "-",
        Area: "	52 809,601 km²",
        Municipios: "167",
        Municipios_Importantes: "Mossoró, Parnamirim, São Gonçalo do Amarante",
        Regiao: "Nordeste",
        Populacao: "3.560.903 hab.",
        Densidade: "67,43 hab./km²",
        Taxa_Urbana: "77.82%",
        Fuso: "UTC−3, America/Sao_Paulo",
        //Economia
        Pib: "R$ 66.970.000.000",
        Pib_Capita: "R$ 19.249,60",
        Arrecadacao: " R$ 695.882.713,49",
        Arrecadacao_Capita: " R$ 195,42",
        Produtos_agricolas: "Melão, abacaxi, cana-de-açúcar, mandioca, mamão, manga",
        Industrias: "Serviços industriais de utilidade pública, Contrução, Derivados de petróleo e biocombustíveis",
        Exportacao: "-",
        //Politica
        Governador: "Fátima Bezerra (PT)",
        Vice: "Antenor Roberto (PCdoB)",
        Presidente_Ass: "Ezequiel Ferreira (PSDB)",
        Qtd_Dep_Est: "24",
        Qtd_Dep_Fed: "8",
        Bancadas: "PSDB, PL, Solidariedade",
        Senador1: "Styvenson Valentim (PODE)",
        Senador2: "Jean Paul Prates (PT)",
        Senador3: "Zenaide Maia (PROS)",
        //Social
        Expectativa_vida: "76,0 anos",
        Mortalidade_infantil: "-",
        Alfabetizacao: "82,6%",
        IDH: "0,731",
        Renda: "R$ 1.077,00",
        Taxa_Ensino_Medio: "61,9%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "73,5%",
        //Racial
        Etnias: "Pardos (52,75%), Brancos (40,84%), Pretos (5,23%), Asiáticos e Indígenas (1,16%)",
        Religioes: "Católicos (73,98%), Protestantes (15,4%), Espíritas (0,8%), Religiões Afro-brasileiras (0,0%), Outras (1,4%), Sem religião (6,4%), Religiões asiáticas (0,0%)",
        //Geografia
        Rios: "Rio Piranhas/Açu, rio Apodi/Mossoró, rio Curimataú, rio Jacu, rio Jundiaí, rio Potengi, rio Seridó ",
        Climas: "Tropical e semiárido",
        Vegetacoes: "Caatinga, Mata Atlântica, Cerrado",
        Relevos: "",
        Divisoes: " ",
        //Imagens
        Imagem_Estado: ["img/estados/riograndedonorte.png"],
        Imagem1: "img/imagens/rn/rn1.jpg",
        Imagem2: "img/imagens/rn/rn2.jpg",
        Imagem3: "img/imagens/rn/rn3.jpg",
        Images: [
            "img/RGDN.png"
        ]
    },
    RioGrandedoSul: {
        Nome: "Rio Grande do Sul",
        Capital: "Porto Alegre",
        Data: "-",
        Area: "281 730,223 km²",
        Municipios: "497",
        Municipios_Importantes: "Caxias do Sul, Canoas, Pelotas",
        Regiao: "Sul",
        Populacao: "11.466.630 hab.",
        Densidade: "40,7 hab./km²",
        Taxa_Urbana: "85.10%",
        Fuso: "UTC−3, America/Fortaleza",
        //Economia
        Pib: "R$ 423,151 bilhões",
        Pib_Capita: "R$ 36.206,54",
        Arrecadacao: " R$ 7.231.404.228,89",
        Arrecadacao_Capita: " R$ 630,65",
        Produtos_agricolas: "Arroz, soja, milho, mandioca, cana-de-açúcar, laranja, alho",
        Industrias: "Construção, Alimentos, Serviços industriais de utilidade pública",
        Exportacao: "-",
        //Politica
        Governador: "Eduardo Leite (PSDB)",
        Vice: "Ranolfo Vieira Júnior (PSDB)",
        Presidente_Ass: "Ernani Polo (PP)",
        Qtd_Dep_Est: "55",
        Qtd_Dep_Fed: "31",
        Bancadas: "MDB, PT, PP",
        Senador1: "Lasier Martins (PODE)",
        Senador2: "Luis Carlos Heinze (PP)",
        Senador3: "Paulo Paim (PT)",
        //Social
        Expectativa_vida: "78,0 anos ",
        Mortalidade_infantil: "9,3‰ nasc.",
        Alfabetizacao: "96,8%",
        IDH: "0,787",
        Renda: "R$ 1.759,00",
        Taxa_Ensino_Medio: "69,2%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "83,8%",
        //Racial
        Etnias: "Brancos (82,3%), Pardos (11,4%), Pretos (5,9%), Asiáticos ou Indígenas (0,4%)",
        Religioes: "Católicos (71,37%), Protestantes (18,3%), Espíritas (3,2%), Religiões Afro-brasileiras (1,5%), Outras (2,3%), Sem religião (5,3%), Religiões asiáticas (0,6%)",
        //Geografia
        Rios: "Rio Jacuí, rio Taquari, rio Caí, rio Gravataí, Lago Guaíba, rio Sinos",
        Climas: "Subtropical úmido e oceânico",
        Vegetacoes: "Campos e florestas",
        Relevos: "",
        Divisoes: " ",
        //Imagens
        Imagem_Estado: ["img/estados/riograndedosul.png"],
        Imagem1: "img/imagens/rs/rs1.jpg",
        Imagem2: "img/imagens/rs/rs2.jpg",
        Imagem3: "img/imagens/rs/rs3.jfif",
        Images: [
            "img/RGDS.png"
        ]
    },
    Rondonia: {
        Nome: "Rondônia",
        Capital: "Porto Velho",
        Data: "13 de setembro de 1943",
        Area: "	237 590,543 km² ",
        Municipios: "52",
        Municipios_Importantes: "Porto Velho, Ji-Paraná, Ariquemes",
        Regiao: "Norte",
        Populacao: "1.815.278 hab",
        Densidade: "7,64 hab./km²",
        Taxa_Urbana: "73.22%",
        Fuso: "UTC−04:00, America/Porto_Velho",
        //Economia
        Pib: "R$47.091 bilhões ",
        Pib_Capita: "R$ 26.497,12",
        Arrecadacao: " R$ 429.665.368,49",
        Arrecadacao_Capita: " R$ 236,69",
        Produtos_agricolas: "Café, cacau, feijão, milho, soja, arroz",
        Industrias: "Serviços industriais de utilidade pública, Construção, Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "Marcos Rocha (PSL)",
        Vice: "Zé Jodan (PSL)",
        Presidente_Ass: "Alex Redano (Republicanos)",
        Qtd_Dep_Est: "24",
        Qtd_Dep_Fed: "8",
        Bancadas: "Republicanos, PODE, MDB",
        Senador1: "Acir Gurgacz (PDT)",
        Senador2: "Confúcio Moura (MDB)",
        Senador3: "Marcos Rogério (DEM)",
        //Social
        Expectativa_vida: "71,5 anos",
        Mortalidade_infantil: "19,9‰ nasc",
        Alfabetizacao: "93,3%",
        IDH: "0,725",
        Renda: "R$ 1.169,00",
        Taxa_Ensino_Medio: "67,4%",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "75,7%",
        //Racial
        Etnias: "",
        Religioes: "Católicos (52,89%), Protestantes (33,8%), Espíritas (0,6%), Religiões Afro-brasileiras (0%), Outras religiões (3,7%), Sem religião (14,3%), Religiões asiáticas (1%)",
        //Geografia
        Rios: "Rio Madeira",
        Climas: " clima tropical úmido",
        Vegetacoes: " floresta pluvial amazônica, cerrados e cerradões ",
        Relevos: "o planalto cristalino, o chapadão e a planície aluvial",
        Divisoes: " ",
        //Images
        Imagem_Estado: ["img/estados/rondonia.png"],
        Imagem1: "img/imagens/ro/ro1.jpg",
        Imagem2: "img/imagens/ro/ro2.jpg",
        Imagem3: "img/imagens/ro/ro3.png",
        Images: [
            "img/Rondonia.png"
        ]
    },
    Roraima: {
        Nome: "Roraima",
        Capital: "Boa Vista",
        Data: "13 de setembro de 1943",
        Area: "224 300,506 km² ",
        Municipios: "15",
        Municipios_Importantes: "Boa Vista, Rorainópolis, Caracaraí",
        Regiao: "Norte",
        Populacao: "652.713 hab",
        Densidade: "2,91 hab./km²",
        Taxa_Urbana: "76.41%",
        Fuso: "UTC−04:00, America/Boa_Vista",
        //Economia
        Pib: "R$ 14,292 bilhões",
        Pib_Capita: "R$ 23.593",
        Arrecadacao: " R$ 127.689.226,96",
        Arrecadacao_Capita: " R$ 195,63",
        Produtos_agricolas: "Café, milho, banana, soja, mandioca",
        Industrias: "Serviços industriais de utilidade pública, Construção, Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "Antonio Denarium (Progressistas)",
        Vice: "Frutuoso Lins (Solidariedade)",
        Presidente_Ass: "Soldado Sampaio (PCdoB)",
        Qtd_Dep_Est: "24",
        Qtd_Dep_Fed: "8",
        Bancadas: "Solidariedade, Republicanos, PT",
        Senador1: "Chico Rodrigues (DEM)",
        Senador2: "Mecias de Jesus (Republicanos)",
        Senador3: "Telmário Mota (PROS)",
        //Social
        Expectativa_vida: "71,2 anos",
        Mortalidade_infantil: " 17,4‰ nasc",
        Alfabetizacao: "90,3% ",
        IDH: "0,752",
        Renda: "R$ 983,00",
        Taxa_Ensino_Medio: "71,9%",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "79,4%",
        //Racial
        Etnias: " Pardos (61,6%), Brancos (30,4 %), Pretos (6,1%), Asiáticos ou Indígenas (1,9 %)",
        Religioes: "Católicos (46,78%), Protestantes (30,3%), Espíritas (0,9%), Religiões Afro-brasileiras (0,1%), Outras (6,6%), Sem religião (13%), Religiões asiáticas (1,2%)",
        //Geografia
        Rios: "Água Boa do Univiní, Ailã, Ajarani, Alalaú, Branco",
        Climas: "Equatorial úmido ",
        Vegetacoes: "floresta tropica, savana, cerrado",
        Relevos: "Planalto Ondulado e os Escarpamentos Setentrionais",
        Divisoes: " ",

        //Racial
        Etnias: "-",
        Religioes: "-",
        Imagem_Estado: ["img/estados/roraima.png"],
        //IMAGENS
        Imagem1: "img/imagens/rr/rr1.jpg",
        Imagem2: "img/imagens/rr/rr2.jpg",
        Imagem3: "img/imagens/rr/rr3.jpg",
        Images: [
            "img/Roraima.png"
        ]
    },
    SantaCatarina: {
        Nome: "Santa Catarina",
        Capital: "Florianópolis",
        Data: " 11 de agosto de 1738",
        Area: "95 736,165 km² ",
        Municipios: "295",
        Municipios_Importantes: "Joinville, Florianópolis , Blumenau ",
        Regiao: "Sul",
        Populacao: " 7.338.473 hab ",
        Densidade: "76,65 hab./km²",
        Taxa_Urbana: "83.99%",
        Fuso: " UTC−3, America/Sao_Paulo ",
        //Economia
        Pib: "R$ 317,000,000 mil ",
        Pib_Capita: " R$ 44.244 ",
        Arrecadacao: " R$ 7.934.383.983,79",
        Arrecadacao_Capita: " R$ 1.081,20",
        Produtos_agricolas: "milho, soja, fumo, mandioca, feijão, arroz, banana, batata inglesa",
        Industrias: "Contrução, Alimentos, Serviços industriais de utilidade pública",
        Exportacao: "-",
        //Politica
        Governador: "Carlos Moisés (PSL) ",
        Vice: "Daniela Reinehr (Sem partido) ",
        Presidente_Ass: "Mauro de Nadal (MDB)",
        Qtd_Dep_Est: "40",
        Qtd_Dep_Fed: "16",
        Bancadas: "MDB, PSL, PSD",
        Senador1: "Dário Berger (MDB) ",
        Senador2: "Esperidião Amin (PP) ",
        Senador3: "Jorginho Mello (PL) ",
        //Social
        Expectativa_vida: "79,9 anos ",
        Mortalidade_infantil: "8,9‰ nasc ",
        Alfabetizacao: "97,2% ",
        IDH: "0,808",
        Renda: "R$ 1.632,00",
        Taxa_Ensino_Medio: "76,8%",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "83,6%",
        //Racial
        Etnias: " Brancos(88,1%), Pardos(9%), Negros2,9%, Amarelos ou Indígenas(0,2%) ",
        Religioes: "Católicos (73%), Evangélicos (20%), Espíritas (1,2%), Religiões Afro-brasileiras (0,2%), Outras (1,8%), Sem religião (3,3%), Religiões asiáticas (0,4%)",
        //Geografia
        Rios: "Rio das Antas, rio Araranguá, rio Bonito",
        Climas: "Subtropical úmido",
        Vegetacoes: "",
        Relevos: " baixada litorânea, Serra do Mar, planalto paleozoico e basáltico",
        Divisoes: " ",
        //Imagens
        Imagem_Estado: ["img/estados/santacatarina.png"],
        Imagem1: "img/imagens/sc/sc1.jpg",
        Imagem2: "img/imagens/sc/sc2.jpg",
        Imagem3: "img/imagens/sc/sc3.jpg",
        Images: [
            "img/SantaCatarina.png"
        ]
    },
    SaoPaulo: {
        Nome: "São Paulo",
        Capital: "São Paulo",
        Data: "-",
        Area: "248 219,481 km²",
        Municipios: "Não sei",
        Municipios_Importantes: "Campinas, São José dos Campos, Sorocaba, Santos",
        Regiao: "Sudeste",
        Populacao: "46.649.132 hab.",
        Densidade: "187,94 hab./km²",
        Taxa_Urbana: "95.88%",
        Fuso: "Não sei",
        //Economia
        Pib: "R$ 2.388.247 trilhões",
        Pib_Capita: "R$ 52.009,94",
        Arrecadacao: " R$ 58.170.827.792,63",
        Arrecadacao_Capita: " R$ 1.246,99",
        Produtos_agricolas: "café, arroz, amendoim, cana-de-açúcar, milho, frutas, soja, legumes e verduras",
        Industrias: "Construção, Derivados de petróleo e biocombustíveis, Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "João Dória (PSDB)",
        Vice: "Rodrigo Garcia (PSDB)",
        Presidente_Ass: "Carlão Pignatari (PSDB)",
        Qtd_Dep_Est: "94",
        Qtd_Dep_Fed: "70",
        Bancadas: "PSL, PT, PSDB",
        Senador1: "José Cerra (PSDB)",
        Senador2: "Alexandre Giordano (MDB)",
        Senador3: "Mara Gabrilli (PSDB)",
        //Social
        Expectativa_vida: "75,4 anos",
        Mortalidade_infantil: "11,05‰ nasc.",
        Alfabetizacao: "97,4%",
        IDH: "0,826",
        Renda: "R$ 1.814",
        Taxa_Ensino_Medio: "77,5%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "87,1%",
        //Racial
        Etnias: "brancos (63,65%), pardos (29,38%), pretos (5,44%), amarelos (1,38%), indígenas (0,11%), sem declaração (90,04%)",
        Religioes: "Católicos (66,12%), Protestantes (24,1%), Espíritas (3,3%), Religiões Afro brasileiras (0,3%), Outras (4,1%), Sem religião (5,1%), Religiões asiáticas (3%)",
        //Geografia
        Rios: "Rio Tiête, rio Paraná, rio Paranapanema, rio Grande, rio Turvo, rio do Peixe, rio Paraíba do Sul, rio Piracicaba, rio Pardo",
        Climas: "Subtropical, tropical de altitude e tropical",
        Vegetacoes: "Mata Atlântica e cerrado" ,
        Relevos: "",
        //Imagens
        Imagem_Estado: ["img/estados/saopaulo.png"],
        Imagem1: "img/imagens/sp/sp1.jpg",
        Imagem2: "img/imagens/sp/sp2.jpg",
        Imagem3: "img/imagens/sp/sp3.jpg",
        Images: [
            "img/SP.png"
        ]
    },
    Sergipe: {
        Nome: "Sergipe",
        Capital: "Aracaju",
        Data: "8 de julho de 1820",
        Area: "21 915,116 km²",
        Municipios: "75",
        Municipios_Importantes: "Aracaju, Nossa Senhora do Socorro, Lagarto",
        Regiao: "Nordeste",
        Populacao: "2.338.474 hab.",
        Densidade: "106,71 hab./km²",
        Taxa_Urbana: "73,5%",
        Fuso: "UTC−3",
        //Economia
        Pib: "R$ 40,704 bilhões",
        Pib_Capita: "R$ 17 789,21",
        Arrecadacao: " R$ 475.375.839,40",
        Arrecadacao_Capita: " R$ 203,28",
        Produtos_agricolas: "frutas cítricas, coco-da-baía, cana-de-açúcar, mandioca e milho",
        Industrias: "Serviços industriais de utilidade pública, Construção, Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "Belivaldo Chagas (PSD)",
        Vice: "Eliane Aquino (PT)",
        Presidente_Ass: "Luciano Bispo de Lima (MDB",
        Qtd_Dep_Est: "24",
        Qtd_Dep_Fed: "8",
        Bancadas: "PSD, PSC, MDB",
        Senador1: "Maria do Carmo Alves (DEM)",
        Senador2: "Alessandro Vieira (Cidadania)",
        Senador3: "Rogério Carvalho (PT)",
        //Social
        Expectativa_vida: "72,4 anos",
        Mortalidade_infantil: "17,0‰ nasc.",
        Alfabetizacao: "83,0% ",
        IDH: "0,702",
        Renda: "R$ 1.028,00",
        Taxa_Ensino_Medio: "46,6%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "76,7%",
        //Racial
        Etnias: "pardos (63%), brancos (30%), negros (5%), indígenas (1%) e outros (1%)",
        Religioes: "Católicos (79,96%), Protestantes (11,8%), Espíritas (1,1%), Religiões Afro-brasileiras (0,2%), Outras (1,9%), Sem religião (8,1%), Religiões asiáticas (0,5%)",
        //Geografia
        Rios: "Rio São Francisco, rio Vasa Barris, rio Sergipe, rio Real, rio Piauí, rio Japaratuba",
        Climas: "Tropical",
        Vegetacoes: "Caatinga, mangues e floresta tropical" ,
        Relevos: "",
        //Imagens
        Imagem_Estado: ["img/estados/sergipe.png"],
        Imagem1: "img/imagens/se/se1.jpg",
        Imagem2: "img/imagens/se/se2.jpg",
        Imagem3: "img/imagens/se/se3.jpg",
        Images: [
            "img/Sergipe.png"
        ]
    },
    Tocantins: {
        Nome: "Tocantins",
        Capital: "Palmas",
        Data: "-",
        Area: "	277 620,914 km²",
        Municipios: "139",
        Municipios_Importantes: "Araguaína, Gurupi, Porto Nacional",
        Regiao: "Norte",
        Populacao: "1.607.363 hab.",
        Densidade: "5,79 hab./km²",
        Taxa_Urbana: "78.81%",
        Fuso: "UTC−3, America/Araguaina",
        //Economia
        Pib: "R$ 39.356.000 bilhões",
        Pib_Capita: "R$ 25.021,80",
        Arrecadacao: " R$ 312.358.531,85",
        Arrecadacao_Capita: " R$ 194,33",
        Produtos_agricolas: "Soja, milho, arroz, abacaxi",
        Industrias: "Serviços industriais de utilidade pública, Construção, Alimentos",
        Exportacao: "-",
        //Politica
        Governador: "Mauro Carlesse (PSL)",
        Vice: "Wanderlei Barbosa (sem partido)",
        Presidente_Ass: "Léo Barbosa (Solidariedade)",
        Qtd_Dep_Est: "24",
        Qtd_Dep_Fed: "8",
        Bancadas: "MDB, Solidariedade, PT",
        Senador1: "Irajá Abreu (PSD)",
        Senador2: "Kátia Abreu (PP)",
        Senador3: "Eduardo Gomes (MDB)",
        //Social
        Expectativa_vida: "73,7 anos",
        Mortalidade_infantil: "15,3‰ nasc.",
        Alfabetizacao: "	90,3%",
        IDH: "0,743",
        Renda: "R$ 1.060,00",
        Taxa_Ensino_Medio: "69,8%",
        Taxa_Ensino_Superior: "-",
        Domicilios_Internet: "71,5%",
        //Racial
        Etnias: "Pardos (68,8%), Brancos (24,2%), Pretos (6,8%), Asiáticos ou Indígenas (0,3%)",
        Religioes: "Católicos (70,60%), Protestantes (23%), Espiritas (0,2%), Religiões Afro-brasileiras (0,0%), Outras (2,2%), Sem religião (5,9%), Religiões asiáticas (0,4%)",
        //Geografia
        Rios: "Rio Tocantins, rio Araguaia, rio das Almas, rio Formoso, rio Garças, rio Bagagem, rio Tocantinzinho, rio Paraná",
        Climas: "Tropical seco e tropical úmido",
        Vegetacoes: "Cerrado" ,
        Relevos: "",
        //Imagens
        Imagem_Estado: ["img/estados/tocantins.png"],
        Imagem1: "img/imagens/to/to1.jpg",
        Imagem2: "img/imagens/to/to2.jpg",
        Imagem3: "img/imagens/to/to3.jpg",
        Images: [
            "img/Tocantins.png"
        ]
    },
    Padrao:{
        Capital: "",
        Data: "",
        Area: "",
        Municipios: "",
        Municipios_Importantes: "",
        Populacao: "",
        Densidade: "",
        Fuso: "",
        //Economia
        Pib: "",
        Pib_Capita: "",
        Arrecadacao: "",
        Arrecadacao_Capita: "",
        Produtos_agricolas: "",
        Industrias: "",
        Exportacao: "",
        //Politica
        Governador: "",
        Vice: "-",
        Presidente_Ass: "",
        Qtd_Dep_Est: "",
        Qtd_Dep_Fed: "",
        Bancadas: "",
        Senadores: "",
        //Social
        Expectativa_vida: "",
        Mortalidade_infantil: "",
        Alfabetizacao: "",
        IDH: "",
        Renda: "",
        Taxa_Ensino_Medio: "",
        Taxa_Ensino_Superior: "",
        Domicilios_Internet: "",
        //Racial
        Etnias: "",
        Religioes: "",
        Imagem_Estado: "",
        Images: [
            
        ]
    }
};