// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DoubleClass","status":false,"description":"Permite que cada personagem tenha duas classes simultaneamente.","parameters":{}},
{"name":"tabuada","status":false,"description":"Adiciona um mini game de batalha baseado em tabuada.","parameters":{}}
];
